// <auto-generated />
using System;
using Examen_2_de_POO.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen_2_de_POO.Migrations
{
    [DbContext(typeof(ContextClientes))]
    partial class ContextClientesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Examen_2_de_POO.Databases.Entities.ClienteEntity", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IdCliente");

                    b.Property<DateTime>("Fechadesembolso")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fechadesembolso");

                    b.Property<DateTime>("Fechaprimerpago")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fechaprimerpago");

                    b.Property<decimal>("Montoprestamo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Montoprestamo");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Tasacomision")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Tasacomision");

                    b.Property<decimal>("Tasainteres")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Tasainteres");

                    b.Property<int>("Termino")
                        .HasColumnType("int")
                        .HasColumnName("Termino");

                    b.HasKey("IdCliente");

                    b.ToTable("clientes", "dbo");
                });

            modelBuilder.Entity("Examen_2_de_POO.Databases.Entities.PlanamortizacionEntity", b =>
                {
                    b.Property<int>("PlanamortizacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PlanamortizacionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanamortizacionId"));

                    b.Property<decimal>("Balanceprincipal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Balanceprincipal");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClienteId");

                    b.Property<int>("Days")
                        .HasColumnType("int")
                        .HasColumnName("Days");

                    b.Property<DateTime>("Fechapago")
                        .HasColumnType("datetime2")
                        .HasColumnName("Fechapago");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Interes");

                    b.Property<int>("Numeroinstalacion")
                        .HasColumnType("int")
                        .HasColumnName("Numeroinstalacion");

                    b.Property<decimal>("PagoNivelSconSVSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PagoNivelSconSVSD");

                    b.Property<decimal>("PagoNivelSinSVSD")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PagoNivelSinSVSD");

                    b.Property<decimal>("Principal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Principal");

                    b.HasKey("PlanamortizacionId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Planamortiguacion", "dbo");
                });

            modelBuilder.Entity("Examen_2_de_POO.Databases.Entities.PlanamortizacionEntity", b =>
                {
                    b.HasOne("Examen_2_de_POO.Databases.Entities.ClienteEntity", "Cliente")
                        .WithMany("PlanamortizacionEntity")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Examen_2_de_POO.Databases.Entities.ClienteEntity", b =>
                {
                    b.Navigation("PlanamortizacionEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
